---
- hosts: all
  tasks:
    - name: ensure development tools are at the latest version
      become: yes
      apt:
        name:
          - build-essential
          - llvm-7-dev
          - lld-7
          - clang-7
          - nasm
          - acpica-tools
          - uuid-dev
          - xauth
          - unzip
          - python3-distutils
          - libglib2.0-dev
          - libfdt-dev
          - libpixman-1-dev
          - zlib1g-dev
          - git-email
          - libaio-dev
          - libbluetooth-dev
          - libbrlapi-dev
          - libbz2-dev
          - libcap-dev
          - libcap-ng-dev
          - libcurl4-gnutls-dev
          - libgtk-3-dev
          - libibverbs-dev
          - libjpeg8-dev
          - libncurses5-dev
          - libnuma-dev
          - librbd-dev
          - librdmacm-dev
          - libsasl2-dev
          - libsdl1.2-dev
          - libseccomp-dev
          - libsnappy-dev
          - libssh2-1-dev
          - libvde-dev
          - libvdeplug-dev
          - libvte-2.91-dev
          - libxen-dev
          - liblzo2-dev
          - valgrind
          - xfslibs-dev
          - libnfs-dev
          - libiscsi-dev
          - ninja-build
          
        state: latest
        install_recommends: no

    - name: set llvm 7 as default
      become: yes
      alternatives:
        name: "{{ item }}"
        link: "/usr/bin/{{ item }}"
        path: "/usr/bin/{{ item }}-7"
      with_items:
        - llvm-PerfectShuffle
        - llvm-ar
        - llvm-as
        - llvm-bcanalyzer
        - llvm-cat
        - llvm-cfi-verify
        - llvm-config
        - llvm-cov
        - llvm-c-test
        - llvm-cvtres
        - llvm-cxxdump
        - llvm-cxxfilt
        - llvm-diff
        - llvm-dis
        - llvm-dlltool
        - llvm-dwarfdump
        - llvm-dwp
        - llvm-exegesis
        - llvm-extract
        - llvm-lib
        - llvm-link
        - llvm-lto
        - llvm-lto2
        - llvm-mc
        - llvm-mca
        - llvm-modextract
        - llvm-mt
        - llvm-nm
        - llvm-objcopy
        - llvm-objdump
        - llvm-opt-report
        - llvm-pdbutil
        - llvm-profdata
        - llvm-ranlib
        - llvm-rc
        - llvm-readelf
        - llvm-readobj
        - llvm-rtdyld
        - llvm-size
        - llvm-split
        - llvm-stress
        - llvm-strings
        - llvm-strip
        - llvm-symbolizer
        - llvm-tblgen
        - llvm-undname
        - llvm-xray
        - ld.lld
        - lld-link
        - clang
        - clang++
        - clang-cpp

    - name: clone qemu repository
      git:
        repo: "https://github.com/qemu/qemu.git"
        dest: "{{ ansible_env.HOME }}/qemu"
        version: "v6.0.0"
        
    - name: build qemu
      shell: "{{ item }}"
      args:
        chdir: "{{ ansible_env.HOME }}/qemu/"
      with_items:
      - ./configure --target-list=x86_64-softmmu
      - make

    - name: clone EDK II repository
      git:
        repo: "https://github.com/tianocore/edk2.git"
        dest: "{{ ansible_env.HOME }}/edk2"
        version: "38c8be123aced4cc8ad5c7e0da9121a181b94251"

    - name: build EDK II base tools
      make:
        chdir: "{{ ansible_env.HOME }}/edk2/BaseTools/Source/C"

    - name: download standard libraries
      unarchive:
        src: "https://github.com/uchan-nos/mikanos-build/releases/download/v2.0/x86_64-elf.tar.gz"
        dest: "{{ ansible_env.HOME }}/osbook/devenv"
        remote_src: yes

    - name: configure display variable if WSL1
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        regexp: "^export DISPLAY="
        line: "export DISPLAY=:0"
      when: "'WSLENV' in ansible_env and 'WSL_INTEROP' not in ansible_env"

    - name: configure display variable if WSL2
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        regexp: "^export DISPLAY="
        line: "export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0"
      when: "'WSL_INTEROP' in ansible_env"
